[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
audio = { path = "crates/audio" }
spotify = { path = "crates/spotify" }
state = { path = "crates/state" }
ui = { path = "crates/ui" }
views = { path = "crates/views" }
workspace = { path = "crates/workspace" }

anyhow = "1.0"
async-trait = "0.1"
bytes = "1"
cpal = "0.16"
dirs = "6.0"
env_logger = "0.11"
gpui = "0.2.2"
gpui-component = "0.5.1"
gpui-component-assets = "0.5.1"
http = "1.3"
log = "0.4"
reqwest = { version = "0.12", default-features = false, features = [
  "rustls-tls-native-roots",
] }
rodio = { version = "0.21", default-features = false, features = ["playback"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

librespot-core = { version = "0.8.0", default-features = false, features = [
  "rustls-tls-native-roots",
] }
librespot-oauth = { version = "0.8.0", default-features = false, features = [
  "rustls-tls-native-roots",
] }
librespot-playback = { version = "0.8.0", default-features = false, features = [
  "rodio-backend",
  "rustls-tls-native-roots",
] }
librespot-protocol = "0.8.0"
protobuf = "3"
tokio = { version = "1.53", features = [
  "rt-multi-thread",
  "net",
  "io-util",
  "macros",
] }

[profile.dev]
split-debuginfo = "unpacked"

[patch.crates-io]
gpui = { path = "vendor/gpui" }

[profile.dev.package."*"]
debug = false
opt-level = 2
